name: armTemplateDeployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDS}}

      - name: Deploy Resource Group rg-githubactions-test
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 2ca69f6a-bdaf-49aa-a407-7b487eed4bf5
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="Australia East"
            resourceGroupName=rg-githubactions-test
          deploymentName: rg-githubactions-test

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountNameDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions-test
          subscriptionId: 2ca69f6a-bdaf-49aa-a407-7b487eed4bf5
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globosg002
            location="Australia East"
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}
